# Generated by Django 5.1.5 on 2025-01-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_thumbnail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
