# Generated by Django 5.1.6 on 2025-02-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picAI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictureai',
            name='img_thumbnail',
        ),
        migrations.AddField(
            model_name='pictureai',
            name='image',
            field=models.ImageField(default='profilepic.jpg', upload_to='profilepicture'),
        ),
    ]
