# Generated by Django 5.1.6 on 2025-02-06 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picAI', '0002_remove_pictureai_img_thumbnail_pictureai_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureai',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pictureai',
            name='image',
            field=models.ImageField(default='profilepic.jpg', upload_to='profilepictureAI'),
        ),
    ]
