# Generated by Django 5.1.6 on 2025-02-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picAI', '0003_pictureai_user_alter_pictureai_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictureai',
            name='user',
        ),
    ]
