# Generated by Django 5.1.6 on 2025-02-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picAI', '0004_remove_pictureai_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictureai',
            name='image',
        ),
    ]
