# Generated by Django 5.1.6 on 2025-02-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picAI', '0005_remove_pictureai_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureai',
            name='img_AI',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
